#!/bin/sh

exec 0</dev/console 1>/dev/console 2>/dev/console

echo "[INITRAMFS] Bootando..."

# Montar pseudo-filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

echo "[INITRAMFS] Detectando dispositivos..."
sleep 2  # dá tempo para o kernel popular /dev

mkdir -p /newroot

is_valid_root() {
    [ -x /newroot/sbin/init ] && return 0
    [ -x /newroot/init ] && return 0
    return 1
}

try_mount() {
    DEV="$1"
    echo "[INITRAMFS] Testando $DEV..."

    mount -o ro "$DEV" /newroot 2>/dev/null || return 1

    if is_valid_root; then
        echo "[INITRAMFS] Root válido encontrado em $DEV"
        return 0
    fi

    umount /newroot
    return 1
}

ROOTDEV=$(cat /proc/cmdline | sed -n 's/.*root=\([^ ]*\).*/\1/p')

if [ -n "$ROOTDEV" ] && [ -b "$ROOTDEV" ]; then
    try_mount "$ROOTDEV" && FOUND="$ROOTDEV"
fi


FOUND=""

# Busca automática por partições comuns
for DEV in /dev/sd* /dev/vd* /dev/hd* /dev/nvme*n*p*; do
    [ -b "$DEV" ] || continue
    try_mount "$DEV" && { FOUND="$DEV"; break; }
done

if [ -n "$FOUND" ]; then
    echo "[INITRAMFS] Preparando switch_root..."

    mount --move /proc /newroot/proc
    mount --move /sys /newroot/sys
    mount --move /dev /newroot/dev

    echo "[INITRAMFS] Executando switch_root..."
    exec switch_root /newroot /sbin/init
fi

##################################################
# Fallback seguro
##################################################
rm /newroot

echo
echo "[INITRAMFS] Nenhuma instalação encontrada."
echo "[INITRAMFS] Entrando em modo básico."
echo
echo "[INITRAMFS] Criando chaves SSH..."
dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key
dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key

exec /bin/sh
